import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Sidebar from "@/components/sidebar"
import { CartProvider } from "@/context/CartContext";
import Footer from "@/components/footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={inter.className}>
      <div className="layout">
        <Header />
        <div className="main-content">
          <Sidebar />
          <div className="content">
          <CartProvider>
          {children}
          </CartProvider>
            <Footer/>
          </div>
        </div>
      </div>
    </body>
  </html>
  );
}
